// Code generated by protoc-gen-go. DO NOT EDIT.
// source: master_pb.proto

package pb_master

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 服务发现相关定义
type DiscoveryRequest struct {
	WorkId               string   `protobuf:"bytes,1,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	Host                 string   `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Load                 int64    `protobuf:"varint,3,opt,name=load,proto3" json:"load,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiscoveryRequest) Reset()         { *m = DiscoveryRequest{} }
func (m *DiscoveryRequest) String() string { return proto.CompactTextString(m) }
func (*DiscoveryRequest) ProtoMessage()    {}
func (*DiscoveryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba11a1a4007e8de2, []int{0}
}

func (m *DiscoveryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscoveryRequest.Unmarshal(m, b)
}
func (m *DiscoveryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscoveryRequest.Marshal(b, m, deterministic)
}
func (m *DiscoveryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscoveryRequest.Merge(m, src)
}
func (m *DiscoveryRequest) XXX_Size() int {
	return xxx_messageInfo_DiscoveryRequest.Size(m)
}
func (m *DiscoveryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscoveryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DiscoveryRequest proto.InternalMessageInfo

func (m *DiscoveryRequest) GetWorkId() string {
	if m != nil {
		return m.WorkId
	}
	return ""
}

func (m *DiscoveryRequest) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *DiscoveryRequest) GetLoad() int64 {
	if m != nil {
		return m.Load
	}
	return 0
}

type DiscoveryResponse struct {
	WorkId               string   `protobuf:"bytes,1,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiscoveryResponse) Reset()         { *m = DiscoveryResponse{} }
func (m *DiscoveryResponse) String() string { return proto.CompactTextString(m) }
func (*DiscoveryResponse) ProtoMessage()    {}
func (*DiscoveryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba11a1a4007e8de2, []int{1}
}

func (m *DiscoveryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscoveryResponse.Unmarshal(m, b)
}
func (m *DiscoveryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscoveryResponse.Marshal(b, m, deterministic)
}
func (m *DiscoveryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscoveryResponse.Merge(m, src)
}
func (m *DiscoveryResponse) XXX_Size() int {
	return xxx_messageInfo_DiscoveryResponse.Size(m)
}
func (m *DiscoveryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscoveryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DiscoveryResponse proto.InternalMessageInfo

func (m *DiscoveryResponse) GetWorkId() string {
	if m != nil {
		return m.WorkId
	}
	return ""
}

// 接受work任务相关定义
type DomainItem struct {
	Domain               string   `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	DnsHost              string   `protobuf:"bytes,2,opt,name=dnsHost,proto3" json:"dnsHost,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DomainItem) Reset()         { *m = DomainItem{} }
func (m *DomainItem) String() string { return proto.CompactTextString(m) }
func (*DomainItem) ProtoMessage()    {}
func (*DomainItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba11a1a4007e8de2, []int{2}
}

func (m *DomainItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DomainItem.Unmarshal(m, b)
}
func (m *DomainItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DomainItem.Marshal(b, m, deterministic)
}
func (m *DomainItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DomainItem.Merge(m, src)
}
func (m *DomainItem) XXX_Size() int {
	return xxx_messageInfo_DomainItem.Size(m)
}
func (m *DomainItem) XXX_DiscardUnknown() {
	xxx_messageInfo_DomainItem.DiscardUnknown(m)
}

var xxx_messageInfo_DomainItem proto.InternalMessageInfo

func (m *DomainItem) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *DomainItem) GetDnsHost() string {
	if m != nil {
		return m.DnsHost
	}
	return ""
}

type TaskReport struct {
	TaskId               string        `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskNum              int64         `protobuf:"varint,2,opt,name=task_num,json=taskNum,proto3" json:"task_num,omitempty"`
	TaskItem             []*DomainItem `protobuf:"bytes,3,rep,name=task_item,json=taskItem,proto3" json:"task_item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TaskReport) Reset()         { *m = TaskReport{} }
func (m *TaskReport) String() string { return proto.CompactTextString(m) }
func (*TaskReport) ProtoMessage()    {}
func (*TaskReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba11a1a4007e8de2, []int{3}
}

func (m *TaskReport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskReport.Unmarshal(m, b)
}
func (m *TaskReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskReport.Marshal(b, m, deterministic)
}
func (m *TaskReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskReport.Merge(m, src)
}
func (m *TaskReport) XXX_Size() int {
	return xxx_messageInfo_TaskReport.Size(m)
}
func (m *TaskReport) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskReport.DiscardUnknown(m)
}

var xxx_messageInfo_TaskReport proto.InternalMessageInfo

func (m *TaskReport) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *TaskReport) GetTaskNum() int64 {
	if m != nil {
		return m.TaskNum
	}
	return 0
}

func (m *TaskReport) GetTaskItem() []*DomainItem {
	if m != nil {
		return m.TaskItem
	}
	return nil
}

type TaskResponse struct {
	StatusCode           int64    `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskResponse) Reset()         { *m = TaskResponse{} }
func (m *TaskResponse) String() string { return proto.CompactTextString(m) }
func (*TaskResponse) ProtoMessage()    {}
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba11a1a4007e8de2, []int{4}
}

func (m *TaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskResponse.Unmarshal(m, b)
}
func (m *TaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskResponse.Marshal(b, m, deterministic)
}
func (m *TaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskResponse.Merge(m, src)
}
func (m *TaskResponse) XXX_Size() int {
	return xxx_messageInfo_TaskResponse.Size(m)
}
func (m *TaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TaskResponse proto.InternalMessageInfo

func (m *TaskResponse) GetStatusCode() int64 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func init() {
	proto.RegisterType((*DiscoveryRequest)(nil), "pb_master.DiscoveryRequest")
	proto.RegisterType((*DiscoveryResponse)(nil), "pb_master.DiscoveryResponse")
	proto.RegisterType((*DomainItem)(nil), "pb_master.DomainItem")
	proto.RegisterType((*TaskReport)(nil), "pb_master.TaskReport")
	proto.RegisterType((*TaskResponse)(nil), "pb_master.TaskResponse")
}

func init() { proto.RegisterFile("master_pb.proto", fileDescriptor_ba11a1a4007e8de2) }

var fileDescriptor_ba11a1a4007e8de2 = []byte{
	// 317 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x4b, 0x4f, 0xf3, 0x30,
	0x10, 0x54, 0x3f, 0x7f, 0x4a, 0xdb, 0x2d, 0xe2, 0x61, 0x09, 0x1a, 0x0a, 0x12, 0x55, 0x4e, 0x3d,
	0xa0, 0x22, 0x85, 0x0b, 0x27, 0x0e, 0x50, 0x24, 0x7a, 0xe1, 0x60, 0x90, 0x7a, 0x8c, 0xdc, 0x7a,
	0x05, 0x51, 0x71, 0x36, 0xd8, 0x0e, 0x88, 0x7f, 0x8f, 0x62, 0xf7, 0x11, 0xf1, 0xb8, 0xcd, 0xcc,
	0x6e, 0x66, 0x76, 0x37, 0x86, 0x3d, 0x2d, 0xad, 0x43, 0x93, 0x95, 0xf3, 0x71, 0x69, 0xc8, 0x11,
	0xef, 0x96, 0xf3, 0x2c, 0x68, 0xc9, 0x23, 0xec, 0x4f, 0x72, 0xbb, 0xa0, 0x77, 0x34, 0x9f, 0x02,
	0xdf, 0x2a, 0xb4, 0x8e, 0xf7, 0xa1, 0xfd, 0x41, 0x66, 0x99, 0xe5, 0x2a, 0x6e, 0x0d, 0x5b, 0xa3,
	0xae, 0x88, 0x6a, 0x3a, 0x55, 0x9c, 0xc3, 0xff, 0x17, 0xb2, 0x2e, 0xfe, 0xe7, 0x55, 0x8f, 0x6b,
	0xed, 0x95, 0xa4, 0x8a, 0xd9, 0xb0, 0x35, 0x62, 0xc2, 0xe3, 0xe4, 0x1c, 0x0e, 0x1a, 0xa6, 0xb6,
	0xa4, 0xc2, 0xe2, 0x9f, 0xae, 0xc9, 0x35, 0xc0, 0x84, 0xb4, 0xcc, 0x8b, 0xa9, 0x43, 0xcd, 0x8f,
	0x20, 0x52, 0x9e, 0xad, 0xbb, 0x02, 0xe3, 0x31, 0xb4, 0x55, 0x61, 0xef, 0xb7, 0xf1, 0x6b, 0x9a,
	0x38, 0x80, 0x27, 0x69, 0x97, 0x02, 0x4b, 0x32, 0x7e, 0x78, 0x27, 0x6d, 0x33, 0xa6, 0xa6, 0x53,
	0xc5, 0x8f, 0xa1, 0xe3, 0x0b, 0x45, 0xa5, 0xbd, 0x03, 0x13, 0xbe, 0xf1, 0xa1, 0xd2, 0x3c, 0x85,
	0x6e, 0xf8, 0xc6, 0xa1, 0x8e, 0xd9, 0x90, 0x8d, 0x7a, 0xe9, 0xe1, 0x78, 0x73, 0xa3, 0xf1, 0x76,
	0x3a, 0xe1, 0x2d, 0x6a, 0x94, 0x5c, 0xc0, 0x4e, 0x48, 0x5d, 0xad, 0x77, 0x06, 0x3d, 0xeb, 0xa4,
	0xab, 0x6c, 0xb6, 0x20, 0x85, 0x3e, 0x9b, 0x09, 0x08, 0xd2, 0x2d, 0x29, 0x4c, 0x67, 0xb0, 0x2b,
	0xf0, 0x39, 0xaf, 0x1d, 0x51, 0xcd, 0xc8, 0x2c, 0xf9, 0x1d, 0x74, 0xd6, 0x0a, 0x3f, 0x69, 0xe6,
	0x7d, 0xfb, 0x21, 0x83, 0xd3, 0xdf, 0x8b, 0x21, 0x39, 0xbd, 0x81, 0x68, 0xb5, 0xfb, 0xd5, 0x06,
	0x35, 0xc7, 0xdf, 0x1e, 0x67, 0xd0, 0xff, 0x21, 0x07, 0x8f, 0x79, 0xe4, 0x1f, 0xc6, 0xe5, 0x57,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x5e, 0x0b, 0x20, 0x86, 0x2b, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RegisteredWorkClient is the client API for RegisteredWork service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RegisteredWorkClient interface {
	Register(ctx context.Context, in *DiscoveryRequest, opts ...grpc.CallOption) (*DiscoveryResponse, error)
}

type registeredWorkClient struct {
	cc *grpc.ClientConn
}

func NewRegisteredWorkClient(cc *grpc.ClientConn) RegisteredWorkClient {
	return &registeredWorkClient{cc}
}

func (c *registeredWorkClient) Register(ctx context.Context, in *DiscoveryRequest, opts ...grpc.CallOption) (*DiscoveryResponse, error) {
	out := new(DiscoveryResponse)
	err := c.cc.Invoke(ctx, "/pb_master.RegisteredWork/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegisteredWorkServer is the server API for RegisteredWork service.
type RegisteredWorkServer interface {
	Register(context.Context, *DiscoveryRequest) (*DiscoveryResponse, error)
}

// UnimplementedRegisteredWorkServer can be embedded to have forward compatible implementations.
type UnimplementedRegisteredWorkServer struct {
}

func (*UnimplementedRegisteredWorkServer) Register(ctx context.Context, req *DiscoveryRequest) (*DiscoveryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}

func RegisterRegisteredWorkServer(s *grpc.Server, srv RegisteredWorkServer) {
	s.RegisterService(&_RegisteredWork_serviceDesc, srv)
}

func _RegisteredWork_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscoveryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegisteredWorkServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb_master.RegisteredWork/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegisteredWorkServer).Register(ctx, req.(*DiscoveryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RegisteredWork_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb_master.RegisteredWork",
	HandlerType: (*RegisteredWorkServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _RegisteredWork_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "master_pb.proto",
}

// ReportClient is the client API for Report service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReportClient interface {
	Report(ctx context.Context, in *TaskReport, opts ...grpc.CallOption) (*TaskResponse, error)
}

type reportClient struct {
	cc *grpc.ClientConn
}

func NewReportClient(cc *grpc.ClientConn) ReportClient {
	return &reportClient{cc}
}

func (c *reportClient) Report(ctx context.Context, in *TaskReport, opts ...grpc.CallOption) (*TaskResponse, error) {
	out := new(TaskResponse)
	err := c.cc.Invoke(ctx, "/pb_master.Report/Report", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReportServer is the server API for Report service.
type ReportServer interface {
	Report(context.Context, *TaskReport) (*TaskResponse, error)
}

// UnimplementedReportServer can be embedded to have forward compatible implementations.
type UnimplementedReportServer struct {
}

func (*UnimplementedReportServer) Report(ctx context.Context, req *TaskReport) (*TaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Report not implemented")
}

func RegisterReportServer(s *grpc.Server, srv ReportServer) {
	s.RegisterService(&_Report_serviceDesc, srv)
}

func _Report_Report_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServer).Report(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb_master.Report/Report",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServer).Report(ctx, req.(*TaskReport))
	}
	return interceptor(ctx, in, info, handler)
}

var _Report_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb_master.Report",
	HandlerType: (*ReportServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Report",
			Handler:    _Report_Report_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "master_pb.proto",
}
