version: '3'
services:
    master:
        build: ./master
        restart: always
        ports: 
            - "8082:8082"
        command: 
            - "0.0.0.0:8082"
            - "master:8083"
    work:
        build: ./work
        restart: always
        depends_on: 
            - master
        command: 
            - "master:8083"
            - "work:8081"
        environment: 
            - "inDocker=indocker"